### ISSUE TITLE
[META] Submodules to port next?

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/metatag#1]
Here's a list of submodules, which should we port (and in which order?)

* [ ] metatag_app_links
* [x] N/A metatag_context
* [ ] metatag_dc
* [ ] metatag_dc_advanced
* [x] metatag_devel
* [x] metatag_facebook
* [x] metatag_favicons
* [ ] metatag_google_cse
* [x] N/A metatag_google_plus
* [ ] metatag_hreflang
* [ ] metatag_importer
* [ ] metatag_mobile
* [x] metatag_opengraph
* [ ] metatag_opengraph_products
* [ ] metatag_panels (metatag_layouts)
* [x] metatag_twitter_cards
* [x] metatag_verification
* [x] metatag_views

---

## Original Issue

From the README:

> This is a pre-release of the meta-tag module. We are currently seeking testers, feedback, and direction on which submodules to work on next.

@jenlampton I'm working on a site that's hopefully going live in February and is using Metatag, so I'm down to help test!

As for direction on which submodules to port next, Facebook, OpenGraph and Twitter Cards are the ones that feel most urgent for my work.

**Comment by jenlampton** [comment]
Thanks for the direction @jackaponte. I agree Facebook, OpenGraph, and Twitter Cards are high on the list, and I would be happy to tackle those next. Unfortunately I seem to be focused on several other sites right now that are getting all my attention. 

If I were to port the modules would you be willing to do most of the testing / feedback and let me know if they are working as expected or not?

**Comment by jackaponte** [comment]
Glad to hear that starting in on those submodules sounds right to you, @jenlampton! And totally understood that you've got other things taking up your attention. All in due time. :)

And yes, I'd certainly be down to do a bunch of testing of those modules, though my own plate is also quite full! Might need some guidance on how to do testing more systematically than just "kick things I'm likely to use until something breaks" unless that's all that's needed. :)

**Comment by jenlampton** [comment]
For the latest release of Metatag I have marked all the unported modules as hidden - but they are still there! I just didn't like the ugliness on the modules page. I'm in the process of wrapping up one (or two?) more backdrop sites here and should be able to get back to this shortly :)

**Comment by jackaponte** [comment]
Hi Jen! That site I mentioned in an earlier content finally went live. :) As a result, just wanted to check in on your plans for porting the Facebook, OpenGraph and Twitter Cards submodules. Do you have any ETA on that work? No worries if not, of course; just want to evaluate how to deal with the site and what to tell the client!

**Comment by jenlampton** [comment]
The Twitter Cards submodule has been ported, and will be in the next release.

**Comment by jenlampton** [comment]
The Facebook submodule has been ported, and will also be in the next release.

**Comment by jenlampton** [comment]
The OpenGraph submodule has been ported, and will also be in the next release.

All three of these submodules are passing tests, but I'm not sure if they are printing out the correct metatags. @jackaponte let me know if you give them a try and they don't seem to be working as they were on Drupal 7.

**Comment by jackaponte** [comment]
Ah--awesome news @jenlampton, thank you! Let me know if you want me to test them in a pull request or just in the next release that comes out; I'll test them as soon as I can!

**Comment by jenlampton** [comment]
I pushed the release last night, so go ahead and test that :)

**Comment by jenlampton** [comment]
I found a problem with the submodules, and fixed them today. Could use some more testing :)

**Comment by jerry-hudgins** [comment]
Thanks for your continuing work on this, Jen. I'd like to register a request to port the Metatag: favicons submodule as well.

**Comment by jenlampton** [comment]
Okay @jerry-hudgins, I'll do that one next :)

**Comment by jenlampton** [comment]
@jerry-hudgins I've ported the favicons submodule  as per commit [37a9da6](https://github.com/backdrop-contrib/metatag/commit/37a9da6cb670fe1183972417d1c1c009fa056540) and have all tests passing. I'd love it if someone could help me test that and confirm that everything is working as it should be before the next release :)

You'll need to grab the latest from https://github.com/backdrop-contrib/metatag

**Comment by jerry-hudgins** [comment]
Great timing for me, @jenlampton, as I have a new site ready to publish that could make use of it. I'll drop it in and see how it behaves this evening. I'll let you know how it goes.

**Comment by jerry-hudgins** [comment]
Working well for me. Thanks, @jenlampton!

**Comment by jenlampton** [comment]
Just cut a new release with Metatag Favicons.  Please keep the recommendations coming :)

**Comment by jerry-hudgins** [comment]
Not to be greedy, I hope, but Metatag: Views comes to mind.

**Comment by jackaponte** [comment]
> Not to be greedy, I hope, but Metatag: Views comes to mind.

Just encountered a strong need for Metatag Views on the Palante Backdrop site, so seconding that hope for Metatag Views! :)

**Comment by ninareyes** [comment]
Thirding that request for Metatag Views!

**Comment by hosef** [comment]
@jenlampton I have made a PR that enables and fixes the Metatag Views module.

**Comment by quicksketch** [comment]
I marked Metatag Views and Metatag Devel as completed.

**Comment by yorkshire-pudding** [comment]
See #98 - I'm not sure that Metatag Views is actually working.
