### ISSUE TITLE
[META] Keep metatag up to date with D7 releases

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/metatag#32]
It looks like there's been a few D7 releases since I've worked on this last. Here's a meta for staying up to date. 

- [x] 7.x-1.22 https://github.com/backdrop-contrib/metatag/issues/41
- [ ] 7.x-1.23 https://github.com/backdrop-contrib/metatag/issues/42
- [ ] 7.x-1.24 https://github.com/backdrop-contrib/metatag/issues/43
- [ ] 7.x-1.25 https://github.com/backdrop-contrib/metatag/issues/44
- [ ] 7.x-1.26 https://github.com/backdrop-contrib/metatag/issues/45
- [ ] 7.x-1.27 https://github.com/backdrop-contrib/metatag/issues/46
