### ISSUE TITLE
Include fixes from Drupal 7.x-1.22

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/metatag#41]
- [x] #2857982 by arosboro: Fixed tests due to changes in Entity Translation.
- [x] #2864524 by JamesK: Improve field description for the abstract meta tag.
- [x] #2882703 by smustgrave: module_load_include() doesn't work quite as intended if the module is not installed.
- [x] #2297647 by greggles, DamienMcKenna: Run views_invalidate_cache() when metatag_views is disabled.

* N/A by DamienMcKenna: Drupal core 7.40 is the minimum version supported.
* N/A #2868750 by DamienMcKenna: List Metatag Cxense as a related module.
* N/A #2882048 by jyraya: i18n integration shouldn't assume a tag has a group.
* N/A #2864834 by DamienMcKenna: Added a note to update script 7114 to note that output caching has been disabled.
* N/A #2857088 by arosboro: Fixed parsing of percentages in URLs in Metatag:Panels.
