### ISSUE TITLE
Include changes from Drupal 7.x-1.27

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/metatag#46]
### Bug

- [ ] | #3108311 by mvc, DamienMcKenna: Meta tags not working with taxonomy terms Views page ending in /all.
- [ ] | #3102817 by DamienMcKenna, ron_s, steveoriol, jmouse888, mattlt, slovv, joekings: Summary token filtering from #3063056 breaks content displays.
- [ ] | #3104933 by DamienMcKenna, ron_s: Revert #3037874 for breaking Panels support.

### Feature

- [ ] | #3109898 by malcolm_p, DamienMcKenna: metatag_requirements() loads slowly due to system_rebuild_module_data().
- [ ] | #2403349 by DamienMcKenna, pvhee, thejimbirch: Convert "author" tag to HTML 5.2 spec.

### Task

- [ ] | #3112549 by DamienMcKenna: Rename test files to PascalCase.
- [ ] | #3107119 by DamienMcKenna: Improve in-module text, meta tag descriptions, etc.
- [ ] | #3112410 by DamienMcKenna: Only run token logic if node:summary token used
- [ ] | #3112422 by DamienMcKenna: Combine submodule "TagsTest" and "Test" tests
- [ ] | #3037874 by DamienMcKenna, ron_s: Revert #3037874 for breaking Panels support.
- [ ] | #3047486 by DamienMcKenna: Fixed hook_requirements message about Fast Token Browser module.
